"""add users and transaction user relationship

Revision ID: f2ad8cfb6c81
Revises: 
Create Date: 2026-10-02 12:11:10.725170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ad8cfb6c81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
    'transactions',
    sa.Column('user_id', sa.Integer(), nullable=True)
)

    op.create_foreign_key(
        'fk_transactions_user_id',
        'transactions',
        'users',
        ['user_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    'fk_transactions_user_id',
    'transactions',
    type_='foreignkey'
)
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###
